/*
 * Todo
 *
 * Sample todo-api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using ToDoAspCore.Attributes;
using ToDoAspCore.Models;
using ToDoAspCore.Services;

namespace ToDoAspCore.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class TodoServiceApiController : ControllerBase
    {
        private readonly IServiceProvider _provider;

        public TodoServiceApiController(IServiceProvider provider)
        {
            this._provider = provider;
            
        }


        private List<Todo> GetTodosForUser(string user)
        {
            return ((ITodoServiceRepository) _provider.GetService(typeof(ITodoServiceRepository))).UsersTodos(user);
        }
        
        /// <summary>
        /// addTodo
        /// </summary>
        /// <param name="user"></param>
        /// <param name="todo"></param>
        /// <response code="201"></response>
        [HttpPost]
        [Route("/todo/{user}")]
        [ValidateModelState]
        [SwaggerOperation("AddTodo")]
        [SwaggerResponse(statusCode: 201, type: typeof(List<Todo>), description: "")]
        public virtual IActionResult AddTodo([FromRoute][Required]string user, [FromBody]Todo todo)
        {
            if (todo.Id == null)
            {
                todo.Id = new Guid().ToString();
            }

            var todos = GetTodosForUser(user);
            
            todos.Add(todo);
            
            var result = new ObjectResult(todos);
            result.StatusCode = 201;
            return result;
        }

        /// <summary>
        /// listTodos
        /// </summary>
        /// <param name="user"></param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("/todo/{user}")]
        [ValidateModelState]
        [SwaggerOperation("ListTodos")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Todo>), description: "")]
        public virtual IActionResult ListTodos([FromRoute][Required]string user)
        {
            var result = new ObjectResult(GetTodosForUser(user));
            result.StatusCode = 200;
            return result;
        }

        /// <summary>
        /// removeAll
        /// </summary>
        /// <param name="user"></param>
        /// <response code="204"></response>
        [HttpDelete]
        [Route("/todo/{user}")]
        [ValidateModelState]
        [SwaggerOperation("RemoveAllTodos")]
        public virtual IActionResult RemoveAllTodos([FromRoute][Required]string user)
        { 
            GetTodosForUser(user).Clear();

            return StatusCode(204);
        }

        /// <summary>
        /// removeTodo
        /// </summary>
        /// <param name="user"></param>
        /// <param name="id"></param>
        /// <response code="200"></response>
        [HttpDelete]
        [Route("/todo/{user}/{id}")]
        [ValidateModelState]
        [SwaggerOperation("RemoveTodo")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Todo>), description: "")]
        public virtual IActionResult RemoveTodo([FromRoute][Required]string user, [FromRoute][Required]string id)
        {
            var todos = GetTodosForUser(user);
            todos.RemoveAll((t) => t.Id == id);
            var result = new ObjectResult(todos);
            result.StatusCode = 200;
            return result;
        }

        /// <summary>
        /// resolveTodo
        /// </summary>
        /// <param name="id"></param>
        /// <param name="user"></param>
        /// <response code="200"></response>
        [HttpPut]
        [Route("/todo/{user}/{id}/resolve")]
        [ValidateModelState]
        [SwaggerOperation("ResolveTodo")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Todo>), description: "")]
        public virtual IActionResult ResolveTodo([FromRoute][Required]string id, [FromRoute][Required]string user)
        {
            var todos = GetTodosForUser(user);
            foreach (var todo in todos)
            {
                if (todo.Id == id)
                {
                    todo.Resolved = true;
                }
            }
            
            var result = new ObjectResult(todos);
            result.StatusCode = 200;
            return result;
        }
    }
}
