== Description
Frontend Todo app to demonstrate the usage of FeatureHub Javascript/Typescript SDK with React front-end framework.


Demonstrates the feature of "STRING" type that controls the colour of a "SUBMIT" button. For example, you can set it as "green", "orange" etc..

In addition, it demonstrates integration with Google Analytics. You will require to have valid GA Tracking ID, e.g. 'UA-XXXXXXXXX-X',
and so  the code is currently commented out.

=== Pre-requisites

* Node @12 or higher

* You need to setup a feature of type "Feature flag - string" in the FeatureHub Admin Console.
Set feature key to `SUBMIT_COLOR_BUTTON`.

* You are required to have a Service Account created in the FeatureHub Admin Console with the "read" permissions for your desired environment.
Once this is set, copy the SDK URL from the Service Accounts page for your desired environment and set it as an environment variable:

You need to append at the front of it the edge url and it's port, like this `'http://[featurehub-edge-url]:[featurehub-edge-port]/features/[copied-sdk-url]`

For example: `http://your-server:8553/features/default/4e439d38-1e87-4e77-84c3-2a32c112cfc5/Fpy5YpEfTeR5yQ15DUWEyvpQyfpjKHefMq9QhlodNzN8XH4by048X9Vjlj94fPieNc5nkagdfVoeAJxM` 

Note, the port will depend on which FeatureHub installation you are running.
If you are running SSE by itself, or the Docker with "all-separate-postgres" it will default to 8553. If you are running Party Server, it will be 8903, if you are running Docker with All-In-One-h2 it will be 8085

You need to specify them in the `public/featurehub-config.json` file and the application will load
them. This is not particularly a recommended practice, it is simply easy for us to use when running in a docker
environment rather than having to search/replace in a large js file.

* If you like to see events fire in your Google Analytics, you will require to have valid GA Tracking ID, e.g. 'UA-XXXXXXXXX-X'.

You also need to specify a CID - a customer id this is associate with GA. In this example it is set to a random number.

Read more about CID https://stackoverflow.com/questions/14227331/what-is-the-client-id-when-sending-tracking-data-to-google-analytics-via-the-mea[here]

GA events:

`name: "todo-add", value: "10"`

`name: "todo-delete", value: "5"`

Once you launch the app, any interaction with "add" or "delete" buttons will generate a GA event accordingly.

More on GA integration can be found here https://docs.featurehub.io/analytics.html


== Installation Instructions

Install dependencies

`npm install`

Generate AXIOS openapi client

`mvn clean generate-sources`

`npm run-script compile`

`npm run-script start`





